import os
import json
import pandas as pd
from PyQt5 import QtCore, QtGui, QtWidgets

json_file = "student_information.json"
xlsx_file = "student_information.xlsx"

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(464, 606)
        MainWindow.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 10, 451, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label.setAutoFillBackground(False)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 80, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.familyname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.familyname_lineEdit.setGeometry(QtCore.QRect(160, 80, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.familyname_lineEdit.setFont(font)
        self.familyname_lineEdit.setObjectName("familyname_lineEdit")
        self.firstname_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.firstname_lineEdit.setGeometry(QtCore.QRect(160, 120, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.firstname_lineEdit.setFont(font)
        self.firstname_lineEdit.setObjectName("firstname_lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(40, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.label_3.setObjectName("label_3")
        self.dateofbirth_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.dateofbirth_lineEdit.setGeometry(QtCore.QRect(160, 160, 171, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.dateofbirth_lineEdit.setFont(font)
        self.dateofbirth_lineEdit.setObjectName("dateofbirth_lineEdit")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(40, 160, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(340, 160, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(340, 120, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(340, 80, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(40, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.math_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.math_lineEdit.setGeometry(QtCore.QRect(110, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.math_lineEdit.setFont(font)
        self.math_lineEdit.setObjectName("math_lineEdit")
        self.english_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.english_lineEdit.setGeometry(QtCore.QRect(320, 290, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.english_lineEdit.setFont(font)
        self.english_lineEdit.setObjectName("english_lineEdit")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(230, 290, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(230, 340, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(40, 340, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.chemistry_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.chemistry_lineEdit.setGeometry(QtCore.QRect(110, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chemistry_lineEdit.setFont(font)
        self.chemistry_lineEdit.setText("")
        self.chemistry_lineEdit.setObjectName("chemistry_lineEdit")
        self.physics_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.physics_lineEdit.setGeometry(QtCore.QRect(320, 340, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.physics_lineEdit.setFont(font)
        self.physics_lineEdit.setText("")
        self.physics_lineEdit.setObjectName("physics_lineEdit")
        self.chinese_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.chinese_lineEdit.setGeometry(QtCore.QRect(110, 390, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chinese_lineEdit.setFont(font)
        self.chinese_lineEdit.setText("")
        self.chinese_lineEdit.setObjectName("chinese_lineEdit")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(40, 390, 61, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.biology_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.biology_lineEdit.setGeometry(QtCore.QRect(320, 390, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.biology_lineEdit.setFont(font)
        self.biology_lineEdit.setText("")
        self.biology_lineEdit.setObjectName("biology_lineEdit")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(230, 390, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(0, 260, 461, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setLineWidth(1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(0, 50, 461, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_2.setFont(font)
        self.line_2.setLineWidth(1)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.centralwidget)
        self.line_3.setGeometry(QtCore.QRect(0, 490, 461, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.line_3.setFont(font)
        self.line_3.setLineWidth(1)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.export2db_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.export_to_database())
        self.export2db_pushButton.setGeometry(QtCore.QRect(150, 530, 161, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.export2db_pushButton.setFont(font)
        self.export2db_pushButton.setObjectName("export2db_pushButton")
        self.cleardata2_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clear_data_2())
        self.cleardata2_pushButton.setGeometry(QtCore.QRect(190, 440, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cleardata2_pushButton.setFont(font)
        self.cleardata2_pushButton.setObjectName("cleardata2_pushButton")
        self.cleardata1_pushButton = QtWidgets.QPushButton(self.centralwidget, clicked = lambda: self.clear_data_1())
        self.cleardata1_pushButton.setGeometry(QtCore.QRect(190, 210, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cleardata1_pushButton.setFont(font)
        self.cleardata1_pushButton.setObjectName("cleardata1_pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 464, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def clear_data_1(self):
        
        self.familyname_lineEdit.setText("")
        self.firstname_lineEdit.setText("")
        self.dateofbirth_lineEdit.setText("")
        
    def clear_data_2(self):
        
        self.math_lineEdit.setText("")
        self.english_lineEdit.setText("")
        self.physics_lineEdit.setText("")        
        self.chemistry_lineEdit.setText("")   
        self.biology_lineEdit.setText("")   
        self.chinese_lineEdit.setText("")   
        
    def export_to_database(self):
        # Grab student's name and birth of date 
        familyname = self.familyname_lineEdit.text()
        firstname = self.firstname_lineEdit.text()
        dateofbirth = self.dateofbirth_lineEdit.text()
        # Grab student's subject scores
        math = self.math_lineEdit.text()
        english = self.english_lineEdit.text()
        physics = self.physics_lineEdit.text()
        chemistry = self.chemistry_lineEdit.text()
        biology = self.biology_lineEdit.text()
        chinese = self.chinese_lineEdit.text()

        full_name = familyname + " " + firstname
        full_name = full_name.rstrip().lstrip()
        full_name = " ".join([s.capitalize() for s in full_name.split()])
        total = int(math) + int(english) + int(physics) + int(chemistry) + int(biology) + int(chinese)
            
        # create a student dictionary
        info_dict = {"Birth": str(dateofbirth),
                      "Math": int(math),
                      "English": int(english),
                      "Physics": int(physics),
                      "Chemistry": int(chemistry),
                      "Biology": int(biology),
                      "Total": total}
        info_dict = {full_name: info_dict}

        # Save the student dictionary into a JSON file
        if not os.path.exists(json_file):
            with open(json_file, "w") as f:
                json.dump(info_dict, f, indent=4)
        else:
            with open(json_file, "r") as f:
                f_dict = json.load(f)
            f_dict.update(info_dict)
            with open(json_file, "w") as f:
                json.dump(f_dict, f, indent=4)    

        with open(json_file, "r") as f:
            f_dict = json.load(f)
            df = pd.DataFrame.from_dict(f_dict, orient="index")
            df.to_excel(xlsx_file)  
            
        msg = QtWidgets.QMessageBox()
        msg.setWindowTitle("Saved to Database !")
        msg.setText("Data Has Been Saved !") 
        msg.setIcon(QtWidgets.QMessageBox.Information)
        msg.exec_()   

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "sinfo"))
        self.label.setText(_translate("MainWindow", "Student Information Management System"))
        self.label_2.setText(_translate("MainWindow", "Family Name"))
        self.label_3.setText(_translate("MainWindow", "First Name"))
        self.label_4.setText(_translate("MainWindow", "Date of Birth"))
        self.label_5.setText(_translate("MainWindow", "dd/mm/yyyy"))
        self.label_6.setText(_translate("MainWindow", "e.g. John"))
        self.label_7.setText(_translate("MainWindow", "e.g. Smith"))
        self.label_8.setText(_translate("MainWindow", "Math"))
        self.label_9.setText(_translate("MainWindow", "English"))
        self.label_10.setText(_translate("MainWindow", "Chemistry"))
        self.label_11.setText(_translate("MainWindow", "Physics"))
        self.label_12.setText(_translate("MainWindow", "Biology"))
        self.label_13.setText(_translate("MainWindow", "Chinese"))
        self.export2db_pushButton.setText(_translate("MainWindow", "Export to Database"))
        self.cleardata2_pushButton.setText(_translate("MainWindow", "Clear Data"))
        self.cleardata1_pushButton.setText(_translate("MainWindow", "Clear Data"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
